### ISSUE TITLE
Wrong encoding on asian languages

### ISSUE THREAD

**Issue by anatolii-lysenko** [SI4T/SI4T#14]
Storage extension works fine except japanese-like languages. These languages are deployed with question marks. The problem disappear if I roll back changes to cd_storage.conf

It is definitely an issue with encoding but the question is where to fix it. Might some setting in JVM...

**Comment by bkoopman** [comment]
Encoding issues are almost always an issue with JVM settings indeed, up to SDL tridion 2013 SP1, please check out http://elenaserghie.blogspot.nl/2012/01/7-clues-to-solve-character-encoding.html for guidance into making sure encoding is set similar (to UTF-8) along the entire line, I guess this also means checking the encoding on your search collections, something which isn't mentioend in that blog.

For SDL Web 8, most settings ate by default UTF-8, but there still are some possibilities on the micro services they are not set to UTF-8, but I don'r have the details to check/set it at hand.

Try checing if everything is correctly configured to UTF-8 and let us know if that solves the problem or not, and in case you are using Web 8, let me know so I can gather up those details.

**Comment by anatolii-lysenko** [comment]
Thanks,

The issue was solved by setting
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Tridion\Content Delivery\General] registry key
to
"jvmarg1"="-Dfile.encoding=UTF-8"
