### ISSUE TITLE
SearchIndexProcessor is not thread-safe

### ISSUE THREAD

**Issue by quirijnslings** [SI4T/SI4T#27]
The SearchIndexProcessor can cause problems when you publish many items from different publications simultaneously, because of a flaw in the design.
It has to do with the way it handles the SearchIndexer. This class is instantiated dynamically based on configuration. If you use SOLR, you will configure the SolrIndexer, if you use another search engine you will pick another one.

The first time the processor needs a SearchIndexer, it instantiates one dynamically and stores it in a map (as a singleton). It calls the indexer at least 2 times:
- first, it calls one of the 'addXX' methods on the indexer
- second, it calls the commit method

The SearchIndexer implementation will use the first call to prepare data to send, and the second call to actually send it. In the case of the SolrIndexer, it creates Solr Documents in the 'add' calls and submits them to a specific Solr Core in the second call. The commit method has logic to pick a different Solr Core per publication.

The SearchIndexProcessor can run in many threads, because it is triggered from the deployer and that is how the deployer works. But since the indexer is a singleton, there is a chance that the addXX method gets called from different threads (so different publish transactions) before the commit is called. As a result, the collection of documents that get submitted to the Solr Core of publication A, might actually contain documents for a different Solr Core.

You can simply reproduce it by setting up SI4T with SOLR, and publishing a lot of items at once, from 2 different publications. Each publication must be configured to use its own core. Before you start, clean out both cores. After you let this run for a while (I tested with appr 150 transactions), search in both cores for items with the wrong publication ID. I tried it three times, and I invariably ended up with 2 or more incorrect documents.

A possible solution is to create the indexer inside the SearchIndexProcessor every time. To make it slightly more efficient, you can load the configured class once, and cache it in a map as a Class<SearchIndexer>. But the actual instantiation should be done every time.

**Comment by raimondkempees-ah** [comment]
Couple of remarks:

- The SearchIndexProcesser is a singleton, but is purely there to process, load and execute search index actions. The indexers and instantations of those are **not** singleton and are newly instantiated new for each storage configuration.
- Further, commits are by transaction id, which limits commits to a single publication, unless something in Tridion 9.5 has changed.

More likely culprits:

- The SolrIndexer (more specifically, the SolrIndexDispatcher)
- Change in 9.5 deployer (a lot has changed afaik)
- Config issue

**Comment by raimondkempees-ah** [comment]
That commit wasn't meant to close the issue. @quirijnslings can you reopen?
